//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicacion
    {
        public int idAplicacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public int estado { get; set; }
    }
}
