//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplication
    {
        public int idAplicacion { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string correo_empresa { get; set; }
        public string correo_pedidos { get; set; }
        public string nombre_remitente { get; set; }
        public string correo_remitente { get; set; }
        public string nombre_empresa { get; set; }
        public string nombre_aplicacion { get; set; }
        public string sitio_web { get; set; }
        public string simbolo_moneda { get; set; }
        public string moneda { get; set; }
        public string divisa { get; set; }
        public string separador_decimales { get; set; }
        public string separador_miles_millones { get; set; }
        public int estado { get; set; }
    }
}
