//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public int idModulo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string icono { get; set; }
        public string ruta { get; set; }
        public int estado { get; set; }


        public Object ToObject()
        {
            return new
            {
                idModulo,
                titulo,
                descripcion,
                icono,
                ruta,
                estado
            };
        }
    }
}
