//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int idPermiso { get; set; }
        public int idRol { get; set; }
        public int idModulo { get; set; }
        public Nullable<int> idOrganizacion { get; set; }
        public int r { get; set; }
        public int w { get; set; }
        public int u { get; set; }
        public int d { get; set; }
    
        public virtual Modulo Modulo { get; set; }
        public virtual Organizacion Organizacion { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
