//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Apadrinamiento = new HashSet<Apadrinamiento>();
            this.ProcesoAdopcion = new HashSet<ProcesoAdopcion>();
        }
    
        public int idPersona { get; set; }
        public Nullable<int> idOrganizacion { get; set; }
        public int idRol { get; set; }
        public string numero_identificacion { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public int telefono { get; set; }
        public string email { get; set; }
        public string nit { get; set; }
        public string nombreFiscal { get; set; }
        public string direccionFiscal { get; set; }
        public string token { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apadrinamiento> Apadrinamiento { get; set; }
        public virtual Organizacion Organizacion { get; set; }
        public virtual Rol Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesoAdopcion> ProcesoAdopcion { get; set; }
    }
}
