//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Animal> Animal { get; set; }
        public DbSet<Apadrinamiento> Apadrinamiento { get; set; }
        public DbSet<Aplicacion> Aplicacion { get; set; }
        public DbSet<Aplication> Aplication { get; set; }
        public DbSet<Contacto> Contacto { get; set; }
        public DbSet<Donacion> Donacion { get; set; }
        public DbSet<Modulo> Modulo { get; set; }
        public DbSet<Organizacion> Organizacion { get; set; }
        public DbSet<Permiso> Permiso { get; set; }
        public DbSet<Persona> Persona { get; set; }
        public DbSet<ProcesoAdopcion> ProcesoAdopcion { get; set; }
        public DbSet<Publicacion> Publicacion { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Suscripcion> Suscripcion { get; set; }
        public DbSet<TipoPago> TipoPago { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<Imagen> Imagen { get; set; }
        public DbSet<TipoAnimal> TipoAnimal { get; set; }
    
        public virtual ObjectResult<spGetAnimales_Result> spGetAnimales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAnimales_Result>("spGetAnimales");
        }
    
        public virtual ObjectResult<spGetModulos_Result> spGetModulos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetModulos_Result>("spGetModulos");
        }
    
        public virtual int spSetTokenApp(Nullable<int> p_idAplicacion, string p_token, Nullable<System.DateTime> p_expire)
        {
            var p_idAplicacionParameter = p_idAplicacion.HasValue ?
                new ObjectParameter("p_idAplicacion", p_idAplicacion) :
                new ObjectParameter("p_idAplicacion", typeof(int));
    
            var p_tokenParameter = p_token != null ?
                new ObjectParameter("p_token", p_token) :
                new ObjectParameter("p_token", typeof(string));
    
            var p_expireParameter = p_expire.HasValue ?
                new ObjectParameter("p_expire", p_expire) :
                new ObjectParameter("p_expire", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSetTokenApp", p_idAplicacionParameter, p_tokenParameter, p_expireParameter);
        }
    
        public virtual ObjectResult<spOrganizaciones_Result> spOrganizaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spOrganizaciones_Result>("spOrganizaciones");
        }
    }
}
