//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAnimal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoAnimal()
        {
            this.Animal = new HashSet<Animal>();
        }
    
        public int idTipoAnimal { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string img { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string ruta { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animal { get; set; }

        public Object ToObject()
        {
            return new
            {
                idTipoAnimal,
                nombre,
                descripcion,
                img,
                fechaCreacion,
                ruta,
                estado
            };
        }
    }
}
