//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchPetDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioApp
    {
        public UsuarioApp()
        {
            
        }
    
        public int idPersona { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }

        public string password { get; set; }    
        
        public Object ToObject()
        {
            return new
            {
                idPersona,
                nombres,
                apellidos,
                telefono,
                email,
                password


            };
        }

    }
}
